### ISSUE TITLE
Aborted transactions can crash Diplomat

### ISSUE THREAD

**Issue by maxvt** [WeAreFarmGeek/diplomat#134]
My code tests fail with:
```
       expected no Exception, got #<NoMethodError: undefined method `empty?' for nil:NilClass> with backtrace:
         # ./.bundle/ruby/2.3.0/bundler/gems/diplomat-dd4eb143e598/lib/diplomat/kv.rb:242:in `decode_transaction'
         # ./.bundle/ruby/2.3.0/bundler/gems/diplomat-dd4eb143e598/lib/diplomat/kv.rb:237:in `transaction_return'
         # ./.bundle/ruby/2.3.0/bundler/gems/diplomat-dd4eb143e598/lib/diplomat/kv.rb:174:in `txn'
         # ./.bundle/ruby/2.3.0/bundler/gems/diplomat-dd4eb143e598/lib/diplomat/rest_client.rb:43:in `method_missing'
```

I instrumented the failing line:
```
    237: def transaction_return(raw_return, options)
 => 238:   binding.pry
    239:   decoded_return =
    240:     options && options[:decode_values] == false ? raw_return : decode_transaction(raw_return)
    241:   OpenStruct.new decoded_return
    242: end
```

and saw this:
```
[1] pry(#<Diplomat::Kv>)> raw_return
=> {"Results"=>nil,
 "Errors"=>
  [{"OpIndex"=>1, "What"=>"failed index check for key \"our_path\", current modify index 8 != 7"}]}
```

Suggested fix is https://github.com/WeAreFarmGeek/diplomat/pull/133.

**Comment by taharah** [comment]
This was just merged.

**Comment by taharah** [comment]
PS thanks for submitting the fix!
